package com.rental.platform.domain.enums;
public enum NotificationType {
    BOOKING_REQUEST, BOOKING_CONFIRMED, BOOKING_CANCELLED, BOOKING_COMPLETED,
    PAYMENT_RECEIVED, REFUND_ISSUED,
    REVIEW_RECEIVED, MESSAGE_RECEIVED,
    LISTING_APPROVED, LISTING_REJECTED, LISTING_SUSPENDED,
    HOST_APPLICATION_APPROVED, HOST_APPLICATION_REJECTED,
    SYSTEM
}
